### ISSUE TITLE
Setting event source options on recurent events

### ISSUE THREAD

**Issue by bricewge** [2733/icalendar2fullcalendar#3]
I spent several hours on trying to set options for event source. I only managed to do it for non recurring events with `$('#calendar').fullCalendar('addEventSource', {events: fc_events(this.response), color: 'green'})`. 

However I don't know how to do the same with recurring events. I can only get **all** recurring events to have the same options but not to set options per event source on recurring events. 

Without that it's not possible to have consistent colors per event source when the source have both 'normal' and recurrent event.

**Comment by 2733** [comment]
With todays commits I improved per-event styling possibilities:
- each event has a class calculated from its vevent uid
- recur events have `recur-event` class
see the demo for more https://2733.github.io/icalendar2fullcalendar/demo/

**Comment by 2733** [comment]
Todo:
- class for events from the same source

**Comment by 2733** [comment]
Now you can specify additional event properties for each ics source.
Actually you define a partial [fullcalendar event object](http://fullcalendar.io/docs/event_data/Event_Object/) which is merged to the generated ones.
See https://github.com/2733/icalendar2fullcalendar/blob/gh-pages/demo/demo.js#L1-5
